### ISSUE TITLE
RealOp Ultimate board hangs up

### ISSUE THREAD

**Issue by zaitsxl** [RealOpInsightLabs/realopinsight-workstation#70] opened 2015-05-15 09:08 UTC
Hi,

we have RealOp Ultimate board open permanently. After some time it shows some error and then returns to logon screen. After logging back in at works, again for only some time. That's very inconvenient. Can you check?

Regards,
Alexander

**Comment by rchakode** [comment] 2015-05-15 09:16
Hi @zaitsxl,
Perhaps you're running out memory problem due notably to the Mod FastCGI of Apache. 

Log on the serveur and check the number of running RealOpInsight FastCGI process

```
$ ps -edf | grep realopinsight
```

You should probably have a lot of process.

BTW, you would probably consider to restart Apache

```
$ service apache2 restart
```

If this does work, you may also consider to restart your serveur.

You may also want to check your file system usage

Let me know the result.

**Comment by zaitsxl** [comment] 2015-05-15 12:46
Hi,

ok, I guess that should help. But what you propose is nothing but temporary solution, after some time it will hang again. Can we do something permanent?

Regards,
Alexander

**Comment by rchakode** [comment] 2015-05-15 12:58
Sure, the upcoming version of the software will bring tunings concerning this problem.

**Comment by zaitsxl** [comment] 2015-05-15 13:18
Great, when you expect to release it?

2015-05-15 15:58 GMT+03:00 Rodrigue Chakode <notifications@github.com>:

> Sure, the upcoming version of the software will bring tunings concerning
> this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-102391407>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by rchakode** [comment] 2015-05-18 07:50
Likely by the end of this month, we're on testing stage.

**Comment by zaitsxl** [comment] 2015-05-18 08:09
Thanx, we'll wait for it

2015-05-18 10:50 GMT+03:00 Rodrigue Chakode <notifications@github.com>:

> Likely by the end of this month, we're on testing stage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-102954203>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-08 17:00
The new version of RealOpInsight Ultimate is now available, can you check that the problem is fixed?

**Comment by zaitsxl** [comment] 2015-06-08 17:11
Hi,

thanx for notification, we'll test and give you feedback ASAP
 8 июня 2015 г. 20:00 пользователь "jameseriot" <notifications@github.com>
написал:

**Comment by zaitsxl** [comment] 2015-06-09 13:03
Hi,

we've downloaded update package for Ubuntu 13.10 but archive refuses to
open. You sure it isn't broken? Archive for Ubuntu 14.04 works nicely though

Regards,
Alexander

2015-06-08 20:11 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi,
>
> thanx for notification, we'll test and give you feedback ASAP
>  8 июня 2015 г. 20:00 пользователь "jameseriot" <notifications@github.com>
> написал:
>
>> The new version of RealOpInsight Ultimate is now available, can you check
>> that the problem is fixed?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110073377>
>> .
>>
>


-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 13:11
Thanks for the feedback, we'll check and fix that ASAP

**Comment by jameseriot** [comment] 2015-06-09 13:18
Hi @zaitsxl 
I just downloaded and uncompress the archive for Ubuntu 13.10.

I tested will version 2015r2, which version did you test? 
```
$ tar zxf realopinsight-ultimate-2015r2.ubuntu1310.x86_64.tar.gz
$ cd realopinsight-ultimate-2015r2.ubuntu1310.x86_64
$ ls
bin  etc  INSTALL.MANIFEST  install-ultimate-distrib.sh  lib  README_INSTALL  sbin  scripts  sql  var  www
```

**Comment by zaitsxl** [comment] 2015-06-09 13:20
Hi,

I've tested the same but before doing anything I wanted to check what's
inside on my Windows laptop and got an error. Did you use some specific
compression format? Anyway I'll try on roistack directly

Regards,
Alexander

2015-06-09 16:18 GMT+03:00 jameseriot <notifications@github.com>:

> Hi @zaitsxl <https://github.com/zaitsxl>
> I just downloaded and uncompress the archive for Ubuntu 13.10.
>
> I tested will version 2015r2, which version did you test?
>
> $ tar zxf realopinsight-ultimate-2015r2.ubuntu1310.x86_64.tar.gz
> $ cd realopinsight-ultimate-2015r2.ubuntu1310.x86_64
> $ ls
> bin  etc  INSTALL.MANIFEST  install-ultimate-distrib.sh  lib  README_INSTALL  sbin  scripts  sql  var  www
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110354276>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 13:24
I use cygwin.
Perhaps your downloaded file is corrupted.

**Comment by zaitsxl** [comment] 2015-06-09 13:26
Hi,

I've retried downloading with the same failure. Anyway on roistack it
works. BTW looks like you've copied README file from older releases as
installation script name there is wrong :)

Regards,
Alexander

2015-06-09 16:24 GMT+03:00 jameseriot <notifications@github.com>:

> I use cygwin.
> Perhaps your downloaded file is corrupted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110356096>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-06-09 14:21
Hi,

we've installed update patch on our RealOp installation. Now I see either
error 500 screen or just blank page. Restarting Apache helps for some time
but then it happens again. What can I do?

Regards,
Alexander

2015-06-09 16:26 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi,
>
> I've retried downloading with the same failure. Anyway on roistack it
> works. BTW looks like you've copied README file from older releases as
> installation script name there is wrong :)
>
> Regards,
> Alexander
>
> 2015-06-09 16:24 GMT+03:00 jameseriot <notifications@github.com>:
>
>> I use cygwin.
>> Perhaps your downloaded file is corrupted.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110356096>
>> .
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 14:31
what do mean by blank page? can you see the interface of ROI ?

Otherwise, can you check in Apache log if you have something wrong ?

Thanks.

**Comment by zaitsxl** [comment] 2015-06-09 14:37
Hi,

blank page is just nothing. No text or any error messages, just white
background. This is what we see on error.log file:

[Tue Jun 09 16:35:16.693930 2015] [fastcgi:error] [pid 2271:tid
140436177913600] [client 172.22.104.10:53389] FastCGI: incomplete headers
(0 bytes) received from server "/var/www/realopinsight/realopinsight.fcgi",
referer: http://zabbix-board.improve/realopinsight/realopinsight.fcgi
[Tue Jun 09 16:35:16.693948 2015] [:warn] [pid 2267:tid 140436406577024]
FastCGI: (dynamic) server "/var/www/realopinsight/realopinsight.fcgi" (pid
4161) terminated by calling exit with status '0'
[Tue Jun 09 16:35:16.693930 2015] [fastcgi:error] [pid 2271:tid
140436228269824] [client 172.22.104.10:53390] FastCGI: incomplete headers
(0 bytes) received from server "/var/www/realopinsight/realopinsight.fcgi",
referer: http://zabbix-board.improve/realopinsight/realopinsight.fcgi

Regards,
Alexander

2015-06-09 17:31 GMT+03:00 jameseriot <notifications@github.com>:

> what do mean by blank page? can you see the interface of ROI ?
>
> Otherwise, can you check in Apache log if you have something wrong ?
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110380144>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 14:44
This message indicates that the ROI program failed to start, can you check that the file has been updated successfully  ?

```
$ ls -l /var/www/realopinsight/realopinsight.fcgi
```
Then verify that the update date is OK.

**Comment by zaitsxl** [comment] 2015-06-09 14:50
Hi,

root@roistack3:~# ls -l /var/www/realopinsight/realopinsight.fcgi
-rwxr-xr-x 1 root root 3739202 Jun  9 15:25
/var/www/realopinsight/realopinsight.fcgi

Looks ok, what else could it be?

2015-06-09 17:44 GMT+03:00 jameseriot <notifications@github.com>:

> This message indicates that the ROI program failed to start, can you check
> that the file has been updated successfully ?
>
> $ ls -l /var/www/realopinsight/realopinsight.fcgi
>
> Then verify that the update date is OK.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110387668>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 14:54
can you check ROI log, please?.

**Comment by jameseriot** [comment] 2015-06-09 14:56
please also send me the result of  the following command?

ls -l /opt/realopinsight

**Comment by zaitsxl** [comment] 2015-06-09 14:58
Hi,

here you go

root@roistack3:~# ls -l /opt/realopinsight
total 28
drwxr-xr-x 2 root     root     4096 Jun  9 15:25 bin
drwxr-xr-x 2 www-data www-data 4096 Jun  9 16:57 data
drwxr-xr-x 2 www-data www-data 4096 Jun  9 15:25 etc
drwxr-xr-x 2 root     root     4096 Jun  9 15:25 lib
drwxr-xr-x 2 www-data www-data 4096 Dec 16 10:49 log
drwxr-xr-x 2 www-data www-data 4096 Jun  9 16:57 run
drwxr-xr-x 2 www-data www-data 4096 Jun  9 15:25 sbin


2015-06-09 17:56 GMT+03:00 jameseriot <notifications@github.com>:

> please also send me the result of the following command?
>
> ls -l /opt/realopinsight
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110392528>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 15:49
The output seems ok.

To recap, how did you upgrade your system because you said previously that your archive was corrupted ?

Just to get more info

**Comment by zaitsxl** [comment] 2015-06-09 15:53
HI,

I said that I was unable to open it under windows with WinRAR, on roistack
with native tar utility it has extracted without errors

Regards,
Alexander

2015-06-09 18:49 GMT+03:00 jameseriot <notifications@github.com>:

> The output seems ok.
>
> To recap, how did you upgrade your system because you said previously that
> your archive was corrupted ?
>
> Just to get more info
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110409831>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-09 16:40
Weird, I just tried to make upgrade to see if I can reproduce the problem, but not. 

What I can suggest at this time:

* restart your ROI server
* check free memory ($ free -om)
* if nothing wrong after the previous step, rerun the install script and, instead of selecting the upgrade option, select "new installation" (no worry, this will not destroy your data). 

For the last step, I would even suggest you to download a new tarball (to be sure that everything is ok) => but this is not required.

**Comment by jameseriot** [comment] 2015-06-10 09:54
hi @zaitsxl 
Have you fixed your problem ?

**Comment by zaitsxl** [comment] 2015-06-10 11:03
Hi,

yes I've restarted installation script with "Install" option. Now
everything seems better. We'll watch for it for some time. And one more
thing I've discovered is that you went commercial :) Why?

Regards,
Alexander

2015-06-10 12:54 GMT+03:00 jameseriot <notifications@github.com>:

> hi @zaitsxl <https://github.com/zaitsxl>
> Have you fixed your problem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110677052>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-10 11:50
Nice to hear that everything is working fine.

About commercial offer, it's just a matter to meet a recurrent users demand.

However this will not change anything for you (as well as other users) that historically use and contribute to the software: we have decided to offer you perpetual license.

**Comment by zaitsxl** [comment] 2015-06-10 11:54
Hi,

that's good to know, thank you. But how am I supposed to activate that
perpetual license? When I logon under admin now I see activation message at
the bottom

Regards,
Alexander

2015-06-10 14:50 GMT+03:00 jameseriot <notifications@github.com>:

> Nice to hear that everything is working fine.
>
> About commercial offer, it's just a matter to meet a recurrent users
> demand.
>
> However this will not change anything for you (as well as other users)
> that historically use and contribute to the software: we have decided to
> offer you perpetual license.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110715668>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-10 11:57
To have a license token in order to disable the activation message, please send us the result of the following commands executed from your ROI server, by private email (support@realopinsight.com). 

We will send you back a license token. 

* hostname
* hostid

**Comment by zaitsxl** [comment] 2015-06-10 13:13
Hi,

I've just received license key from you. We had board opened on our TV for
the whole day. Now when I tried to open it on my PC it didn't open, after
reloading page couple of times it still shows blank page. And moreover
board on TV disappeared as well showing blank page

Regards,
Alexander

2015-06-10 14:57 GMT+03:00 jameseriot <notifications@github.com>:

> To have a license token in order to disable the activation message, please
> send us the result of the following commands executed from your ROI server,
> by private email (support@realopinsight.com).
>
> We will send you back a license token.
>
>    - hostname
>    - hostid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110717489>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-06-10 13:23
Hi,

and one more thing: activation key doesn't work either :-)

Regards,
Alexander

2015-06-10 16:13 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi,
>
> I've just received license key from you. We had board opened on our TV for
> the whole day. Now when I tried to open it on my PC it didn't open, after
> reloading page couple of times it still shows blank page. And moreover
> board on TV disappeared as well showing blank page
>
> Regards,
> Alexander
>
> 2015-06-10 14:57 GMT+03:00 jameseriot <notifications@github.com>:
>
>> To have a license token in order to disable the activation message,
>> please send us the result of the following commands executed from your ROI
>> server, by private email (support@realopinsight.com).
>>
>> We will send you back a license token.
>>
>>    - hostname
>>    - hostid
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110717489>
>> .
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-10 13:39
When this appears, can you please look at in Apache and ROI logs and let us know if you find something suspect.

Thanks.

**Comment by zaitsxl** [comment] 2015-06-23 08:51
Hi,

FYI today morning board being opened for less than 24 hours showed "out of
memory" error message


On Wed, Jun 10, 2015 at 16:39 PM, jameseriot <notifications@github.com>
wrote:

When this appears, can you please look at in Apache and ROI logs and let us
know if you find something suspect.


Thanks.


—
Reply to this email directly or view it on GitHub
<https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-110757164>
.










-- 
Regards,
Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-06-23 11:18
Hi,
Thanks for the feedback.
We have also identified the memory problem on our installation.
We have started working on that, the next release will mainly focus on  fixing this issue.

**Comment by zaitsxl** [comment] 2015-08-03 14:19
Hi,

any information regarding new release date? We still experience hangs because of memory leak

Regards,
Alexander

**Comment by jameseriot** [comment] 2015-08-03 16:21
Hi Alexander,

We are working heavily on this issue, and the first results are very promising.
As this requires huge changes on code we expect to have at least a first beta release by the end of this month.

We'll let you know when the release will be available.

Regards,
James.

**Comment by jameseriot** [comment] 2015-08-19 13:46
Hi @zaitsxl 

We are releasing the 1st release candidate of RealOpInsight Ultimate 2015r3 that would bring improvements regarding this issue: http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/

You can test it and send feedback. Note that this release comes with a built-in http server to avoid some problem related to Apache + FastCGI. 

As usual the upgrade process shall be transparent, the old Apache config will be disabled.

**Comment by zaitsxl** [comment] 2015-08-19 13:56
Hi,

ok we will test that and give you feedback

2015-08-19 16:46 GMT+03:00 jameseriot <notifications@github.com>:

> Hi @zaitsxl <https://github.com/zaitsxl>
>
> We are releasing the 1st release candidate of RealOpInsight Ultimate
> 2015r3 that would bring improvements regarding this issue:
> http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>
> You can test it and send feedback. Note that this release comes with a
> built-in http server to avoid some problem related to Apache + FastCGI.
>
> As usual the upgrade process shall be transparent, the old Apache config
> will be disabled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132604544>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-08-20 06:37
Hi,

I've just installed updated version and I must say you've done great job,
so many options added, some of them were requested from us. Thanx a lot

2015-08-19 16:56 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi,
>
> ok we will test that and give you feedback
>
> 2015-08-19 16:46 GMT+03:00 jameseriot <notifications@github.com>:
>
>> Hi @zaitsxl <https://github.com/zaitsxl>
>>
>> We are releasing the 1st release candidate of RealOpInsight Ultimate
>> 2015r3 that would bring improvements regarding this issue:
>> http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>>
>> You can test it and send feedback. Note that this release comes with a
>> built-in http server to avoid some problem related to Apache + FastCGI.
>>
>> As usual the upgrade process shall be transparent, the old Apache config
>> will be disabled.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132604544>
>> .
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-08-20 06:43
Hi,

and now about the bad stuff. I cannot add any data source, I've filled up
all the fields I could fill but when I press "Add as source" it says "Fix
fields in red" while none of them is red


2015-08-20 9:37 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi,
>
> I've just installed updated version and I must say you've done great job,
> so many options added, some of them were requested from us. Thanx a lot
>
> 2015-08-19 16:56 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:
>
>> Hi,
>>
>> ok we will test that and give you feedback
>>
>> 2015-08-19 16:46 GMT+03:00 jameseriot <notifications@github.com>:
>>
>>> Hi @zaitsxl <https://github.com/zaitsxl>
>>>
>>> We are releasing the 1st release candidate of RealOpInsight Ultimate
>>> 2015r3 that would bring improvements regarding this issue:
>>> http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>>>
>>> You can test it and send feedback. Note that this release comes with a
>>> built-in http server to avoid some problem related to Apache + FastCGI.
>>>
>>> As usual the upgrade process shall be transparent, the old Apache config
>>> will be disabled.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132604544>
>>> .
>>>
>>
>>
>>
>> --
>> In DOS we trust. Alexander Zaitsev
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-08-20 06:43
here you have the screenshot

2015-08-20 9:43 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi,
>
> and now about the bad stuff. I cannot add any data source, I've filled up
> all the fields I could fill but when I press "Add as source" it says "Fix
> fields in red" while none of them is red
>
>
> 2015-08-20 9:37 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:
>
>> Hi,
>>
>> I've just installed updated version and I must say you've done great job,
>> so many options added, some of them were requested from us. Thanx a lot
>>
>> 2015-08-19 16:56 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:
>>
>>> Hi,
>>>
>>> ok we will test that and give you feedback
>>>
>>> 2015-08-19 16:46 GMT+03:00 jameseriot <notifications@github.com>:
>>>
>>>> Hi @zaitsxl <https://github.com/zaitsxl>
>>>>
>>>> We are releasing the 1st release candidate of RealOpInsight Ultimate
>>>> 2015r3 that would bring improvements regarding this issue:
>>>> http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>>>>
>>>> You can test it and send feedback. Note that this release comes with a
>>>> built-in http server to avoid some problem related to Apache + FastCGI.
>>>>
>>>> As usual the upgrade process shall be transparent, the old Apache
>>>> config will be disabled.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132604544>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> In DOS we trust. Alexander Zaitsev
>>>
>>
>>
>>
>> --
>> In DOS we trust. Alexander Zaitsev
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-08-20 07:49
Hi,

ok previous problem solved, I just had to add slash at the end of URL. Now
another problem: tiles are really big now, most probably they try to
content that large tree structure which is BTW completely useless if you
have 160 items. I tried different display types (complete, no report, only
tiles) but they remain the same. Here you have the screenshot

Regards,
Alexander

2015-08-20 9:43 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> here you have the screenshot
>
> 2015-08-20 9:43 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:
>
>> Hi,
>>
>> and now about the bad stuff. I cannot add any data source, I've filled up
>> all the fields I could fill but when I press "Add as source" it says "Fix
>> fields in red" while none of them is red
>>
>>
>> 2015-08-20 9:37 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:
>>
>>> Hi,
>>>
>>> I've just installed updated version and I must say you've done great
>>> job, so many options added, some of them were requested from us. Thanx a lot
>>>
>>> 2015-08-19 16:56 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:
>>>
>>>> Hi,
>>>>
>>>> ok we will test that and give you feedback
>>>>
>>>> 2015-08-19 16:46 GMT+03:00 jameseriot <notifications@github.com>:
>>>>
>>>>> Hi @zaitsxl <https://github.com/zaitsxl>
>>>>>
>>>>> We are releasing the 1st release candidate of RealOpInsight Ultimate
>>>>> 2015r3 that would bring improvements regarding this issue:
>>>>> http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>>>>>
>>>>> You can test it and send feedback. Note that this release comes with a
>>>>> built-in http server to avoid some problem related to Apache + FastCGI.
>>>>>
>>>>> As usual the upgrade process shall be transparent, the old Apache
>>>>> config will be disabled.
>>>>>
>>>>> —
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132604544>
>>>>> .
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> In DOS we trust. Alexander Zaitsev
>>>>
>>>
>>>
>>>
>>> --
>>> In DOS we trust. Alexander Zaitsev
>>>
>>
>>
>>
>> --
>> In DOS we trust. Alexander Zaitsev
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-08-20 07:51
Hi Alexander,

Thanks for all the feedback.
You omitted to attach the screenshot.

**Comment by jameseriot** [comment] 2015-08-20 07:55
Alexander,
Can you, please, provide a screenshot ?

**Comment by zaitsxl** [comment] 2015-08-20 07:56
Hi,

you have 2 of them there :)

2015-08-20 10:55 GMT+03:00 jameseriot <notifications@github.com>:

> Alexander,
> Can you, please, provide a screenshot ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132923593>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment] 2015-08-20 08:04
I don't know if it's a GitHub problem, but I can't see anything.

**Comment by jameseriot** [comment] 2015-08-20 08:05
Otherwise, you may send that by email support@realopinsight.com

**Comment by zaitsxl** [comment] 2015-08-26 11:09
Hi,

let me inform you that despite we have another kinds of problems now the
initial issue of being out of memory seems to be fixed. We have board open
for more than a day and it's still functional. Waiting for an update
regarding tiles display



2015-08-20 11:05 GMT+03:00 jameseriot <notifications@github.com>:

> Otherwise, you may send that by email support@realopinsight.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-132926276>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by RealOpInsightLabs** [comment] 2015-08-27 09:58
Many thanks for the feedback, we are doing our best to release a fix asap, lively by the end of next week.

**Comment by rchakode** [comment] 2015-08-27 10:36
I'll close this ticket now, as the problem is now related to ticket #79

**Closed by rchakode** 2015-08-27 10:36 UTC
Labels: bug

**Comment by rchakode** [comment] 2015-08-31 12:03
Hi @zaitsxl 
We're release RealOpInsight Ultimate version 2015r3 that fixes this issue: https://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/

Try it and send us feedback.

**Comment by zaitsxl** [comment] 2015-08-31 12:27
Hi Rodrigue,

yes I've just installed new version and you're right, tiles now look as
they should. Though diagrams inside tiles are still present. Thanx, we will
check if memory problem didn't return and give you feedback

Regards,
Alexander

2015-08-31 15:03 GMT+03:00 Rodrigue Chakode <notifications@github.com>:

> Hi @zaitsxl <https://github.com/zaitsxl>
> We're release RealOpInsight Ultimate version 2015r3 that fixes this issue:
> https://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>
> Try it and send us feedback.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-136351715>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by zaitsxl** [comment] 2015-08-31 14:08
Hi Rodrigue,

it worked nicely for some time but now when I try to logon under admin with
default password it shows the attached screenshot and doesn't let me in.
Under another user with operator privileges it works

2015-08-31 15:27 GMT+03:00 Moonwalker <zaits.xl@gmail.com>:

> Hi Rodrigue,
>
> yes I've just installed new version and you're right, tiles now look as
> they should. Though diagrams inside tiles are still present. Thanx, we will
> check if memory problem didn't return and give you feedback
>
> Regards,
> Alexander
>
> 2015-08-31 15:03 GMT+03:00 Rodrigue Chakode <notifications@github.com>:
>
>> Hi @zaitsxl <https://github.com/zaitsxl>
>> We're release RealOpInsight Ultimate version 2015r3 that fixes this
>> issue:
>> https://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/
>>
>> Try it and send us feedback.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-136351715>
>> .
>>
>
>
>
> --
> In DOS we trust. Alexander Zaitsev
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by RealOpInsightLabs** [comment] 2015-08-31 15:58
This is a known issue. Restart the http server, it should work
/etc/init.d/realopinsight-server restart.

We provide a better fix in next release.

**Comment by zaitsxl** [comment] 2015-09-01 05:47
Hi,

yes that helped, thanx

2015-08-31 18:58 GMT+03:00 RealOpInsight Labs <notifications@github.com>:

> This is a known issue. Restart the http server, it should work
> /etc/init.d/realopinsight-server restart.
>
> We provide a better fix in next release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/70#issuecomment-136414553>
> .
>



-- 
In DOS we trust. Alexander Zaitsev
