### ISSUE TITLE
Unknow data source type on migration to 2015r3.b1

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#78] opened 2015-08-24 08:51 UTC
Hi @RealOpInsightLabs,

I apply update from 2015r2 to 2015r3.b1, but I have a source trouble alert.

All my service in realopinsight ultimate are marked as "Unknown data source type" now.

How can I fix that ?

Thanks

**Comment by RealOpInsightLabs** [comment] 2015-08-24 09:21
Hi @bzhpwr, 
Can you go in admin page and verify if something was broken?

**Comment by bzhpwr** [comment] 2015-08-24 09:25
Old configuration is still in "Monitoring Data Sources". So it should work.

I have a production version on Realopinsight (2015r2 I think) and it still work.

I try with realopinsight worstation but i have the same trouble on importing data source.

**Comment by RealOpInsightLabs** [comment] 2015-08-24 09:29
For further investigation, which source type do you use? 
And how your data points are set in description file, I mean, with or without, source Id?

**Comment by bzhpwr** [comment] 2015-08-24 09:44
I not sure about what you want to mean but I think it's was I look after update.
In my .xml files, all sources point have this:

[...]
<SubServices>Source0:SERVER/service</SubServices>
[...]

It's what U mean ?

**Comment by RealOpInsightLabs** [comment] 2015-08-24 09:49
Yes. That's, in part.

in admin page, source0 has which type? Nagios? Zabbix? ...
If Nagios, with or without livestatus.

**Comment by bzhpwr** [comment] 2015-08-24 09:51
Nagios with livestatus.

**Comment by RealOpInsightLabs** [comment] 2015-08-27 09:57
This problem has been identified, and a fix will be released in the next close days.

Thanks again for the report.

**Comment by rchakode** [comment] 2015-08-31 12:05
Hi  @bzhpwr,
We're release RealOpInsight Ultimate 2015r3 that shall fix this issue: 
https://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/

You can also download RealOpInsight Workstation 3.3.1 that also includes that fix: https://sourceforge.net/projects/ngrt4n/files/RealOpInsight/3.3.1/

**Comment by bzhpwr** [comment] 2015-08-31 14:26
Hi @rchakode,
I update my RealOpInsight Ultimate Test Environment to 2015r3 ( Today Release ), but still the same trouble.

I also try with RealOpInsight Workstation 3.3.1, same trouble.

Sorry.

**Comment by bzhpwr** [comment] 2015-08-31 14:55
After trying to update maps:

# service realopinsight-server status
 * realopinsight-server is not running

# service realopinsight-reportd status
 * realopinsight-reportd is running

I have nothing interesting in log/realopinsight.log

Just for my information, does apache2 service need to run with the new version of Rois Ultimate ?

**Comment by bzhpwr** [comment] 2015-08-31 15:02
# It's not the same error ! 

Sorry Now it's:
"Unknown event on Source0:Server/Service." On Rois Ultimate.

And On Workstation:
"Erreur lors du traitement du fichier"

**Comment by rchakode** [comment] 2015-09-01 19:27
Hi @bzhpwr 
We just found a regression due to some refactoring.
However, while the first error seems to be consistent with that regression, the second one seems weird.

Anyway, we just released a nightly build of RealOpInsight Workstation that should fix the regression (we hope finally this time). Please download it, try it out, and let us know if that fixes the issue: http://sourceforge.net/projects/ngrt4n/files/RealOpInsight/nightly/realopinsight-workstation-3.3.2n-wininst.exe/download

After your feedback, and in case of success, we will publish the final releases for RealOpInsight Workstation and RealOpInsight Ultimate. 

Thanks again for your report.

**Comment by bzhpwr** [comment] 2015-09-02 09:19
Hi @rchakode,

It's look like OK :) . I try it on Windows 7 64 bits and I can import data point and use map in Rois Workstation.

Thanks to you for your hard work

**Comment by rchakode** [comment] 2015-09-02 09:26
Nice to hear this, we'll apply the fix and publish new updated releases.

**Comment by RealOpInsightLabs** [comment] 2015-09-04 07:41
Hi,
The releases are now published, you can get them though our downloads page.
Don't hesitate if you have have further feedback or feature requests.

**Comment by bzhpwr** [comment] 2015-09-07 08:17
Hi,

I apply the new releases, it's running since 3 days and it's look working good. Fast, light (Only 400mb in RAM), and beautiful. 

Thanks for your work,

**Comment by RealOpInsightLabs** [comment] 2015-09-07 17:19
Nice to hear this. Thanks for the feedback, the ticket will be closed.

**Closed by RealOpInsightLabs** 2015-09-07 17:19 UTC
Labels: bug
